Traceback (most recent call last):
  File "/home/falmeida/Documents/GitHub/pythonScripts/falmeida-py-runner.py", line 18, in <module>
    from falmeida_py.__main__ import main
  File "/home/falmeida/Documents/GitHub/pythonScripts/falmeida_py/__main__.py", line 47, in <module>
    from docopt import docopt
ModuleNotFoundError: No module named 'docopt'
